

# THEME CONFIGURATION
format = """
[](#36323d)\
$username\
[](bg:#7470ce fg:#36323d)\
$directory\
[](fg:#7470ce bg:#181320)\
$git_branch\
$git_status\
[](fg:#181320 bg:#3fc997)\
$time\
[ ](fg:#3fc997)\
\n$character
"""
# Place between git_status and time
# $rust\
# [](fg:#86BBD8 bg:#33658A)\

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#36323d"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[character]
success_symbol = "[|>](fg:#3fc997)"
error_symbol = "[||>](fg:#db0088)"

[directory]
style = "bg:#7470ce"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#181320"
format = '[[ $symbol $branch ](bg:#181320)]($style)'

[git_status]
style = "bg:#181320"
format = '[[($all_status$ahead_behind )](bg:#181320)]($style)'

# [rust]
# disabled = true
# symbol = ""
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%I:%M" # Hour:Minute Format
style = "bg:#3fc997"
format = '[[ $time ](bg:#3fc997 fg:#0f0c14)]($style)'

