#! /bin/sh

# Launch programs at start
nitrogen --restore &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh
dunst &
picom -f &

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V
bspc monitor -d I II III IV V VI VII VIII IX X 

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Tk state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance state=floating
bspc rule -a Gcolor3 state=floating
